### ISSUE TITLE
IndexError when using get_editor()

### ISSUE THREAD

**Issue by etherealxx** [NodusLorden/gddecoder#1]
Such a cool tool, i used it for copying level. Now i want to use it to, say, remove every startpos from a level. However i encountered this.

```python
from  gddecoder import *

levels = LocalLevels()

level_to_edit : Level = levels.get_level("OverLorder Lyt Pt 1")

if level_to_edit:
    print("Level name : " + level_to_edit[LevelSettings.name])
    editor = level_to_edit.get_editor()
```

Output:
```
Level name : OverLorder Lyt Pt 1
Traceback (most recent call last):
  File "C:\Users\Ethereal\AppData\Local\Temp\tempCodeRunnerFile.python", line 10, in <module>
    editor = level_to_edit.get_editor()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\locallevels.py", line 34, in get_editor
    return Editor(self[LevelSettings.editor])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\level_editor\editor.py", line 31, in __init__
    self.load_properties(level_properties)
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\level_editor\editor.py", line 41, in load_properties       
    self.load_colors(val)
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\level_editor\editor.py", line 56, in load_colors
    set(map(lambda color: self.colors.load_color(color), colors_str.split("|")[:-1]))
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\level_editor\editor.py", line 56, in <lambda>
    set(map(lambda color: self.colors.load_color(color), colors_str.split("|")[:-1]))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ethereal\AppData\Roaming\Python\Python311\site-packages\gddecoder\level_editor\color.py", line 130, in load_color
    self[i - 1] = color
    ~~~~^^^^^^^
IndexError: list assignment index out of range
```

Also, maybe put a license in this repo? Permissive maybe? Thanks.

**Comment by Asm0deus22** [comment]
Did u solved this problem?
@etherealxx
